default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  host: database-1.cl0mfy4msjip.us-east-2.rds.amazonaws.com
  password: <%= ENV['SKILLS_SHOWCASE_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: skills_showcase_development

test:
  <<: *default
  database: skills_showcase_test

production:
  <<: *default
  database: skills_showcase_production
  username: skills_showcase
  password: <%= ENV['SKILLS_SHOWCASE_DATABASE_PASSWORD'] %>
